# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posts_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
