# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instapics.Profile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(to='instapics.tag'),
        ),
    ]
