# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0003_auto_20190521_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(blank=True, to='instapics.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
