# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(default='image displayed', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
