# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0005_auto_20190522_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
