# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0006_auto_20190522_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profiles/'),
        ),
    ]
