# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapics', '0007_auto_20190522_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='profile_picture',
        ),
    ]
